pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t hello-world .'
            }
        }

        stage('Remove Old Container') {
            steps {
                sh 'docker rm -f hello || true'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -d --name hello -p 8081:80 hello-world'
            }
        }

        stage('Verify') {
            steps {
                sh 'docker ps'
            }
        }
    }
}
